In [70]:
# Task1_0530. 고객 정보 데이터프레임과 구매 내역 데이터프레임을 결합하여 각 고객이름(name) 별 총 지출을 계산하여 출력하세요.
import pandas as pd

# 고객 정보 데이터프레임 생성
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'David']
})

# 구매 내역 데이터프레임 생성
purchases = pd.DataFrame({
    'purchase_id': [101, 102, 103, 104, 105],
    'customer_id': [1, 2, 1, 3, 2],
    'amount': [250, 150, 200, 300, 350]
})
print(customers,'\n')
print(purchases,"\n")

# Option-1 using MERGE
MergedDF=pd.merge(customers,purchases, on='customer_id', how='left')
PVM=MergedDF.pivot_table(index='name', values='amount', aggfunc='sum', fill_value=0)
print(PVM,"\n")

# Option-2 using JOIN
JoinedDF = purchases.set_index('customer_id').join(customers.set_index('customer_id'), how='outer')
PVJ=JoinedDF.pivot_table(index='name', values='amount', aggfunc='sum', fill_value=0)
print(PVJ,"\n")

# Option-3 using CONCAT
ConDF = pd.concat([customers, purchases], axis=1)
PVC=JoinedDF.pivot_table(index='name', values='amount', aggfunc='sum', fill_value=0)
print(PVC,"\n")

   customer_id     name
0            1    Alice
1            2      Bob
2            3  Charlie
3            4    David

   purchase_id  customer_id  amount
0          101            1     250
1          102            2     150
2          103            1     200
3          104            3     300
4          105            2     350

         amount
name
Alice       450
Bob         500
Charlie     300
David         0

         amount
name
Alice       450
Bob         500
Charlie     300
David         0

         amount
name
Alice       450
Bob         500
Charlie     300
David         0

In [72]:
# Task2_0530. 학생 성적 데이터프레임과 과목 데이터프레임을 결합하여 각 과목별 평균 성적을 계산하여 출력하세요.
# 학생 성적 데이터프레임 생성
grades = pd.DataFrame({
    'student_id': [1, 2, 3, 4, 1, 2, 3, 4],
    'subject_id': [101, 101, 102, 102, 103, 103, 101, 103],
    'grade': [85, 90, 78, 88, 92, 95, 80, 85]
})

# 과목 데이터프레임 생성
subjects = pd.DataFrame({
    'subject_id': [101, 102, 103],
    'subject_name': ['Math', 'Science', 'History']
})
print(grades,'\n')
print(subjects,'\n')


# Option-1 using MERGE
MergedDF=pd.merge(grades,subjects, on='subject_id', how='left')
PVM=MergedDF.pivot_table(index='student_id', columns='subject_name',values='grade', aggfunc='mean', fill_value=0)
print(PVM,"\n")

# Option-2 using JOIN
JoinedDF = grades.set_index('subject_id').join(subjects.set_index('subject_id'), how='left')
PVJ=JoinedDF.pivot_table(index='student_id', columns='subject_name', values='subject_name', aggfunc='mean', fill_value=0)
print(PVJ,"\n")

# Option-3 using CONCAT
ConDF = pd.concat([grades, subjects], axis=1)
PVC=JoinedDF.pivot_table(index='student_id', columns='subject_name', values='subject_name', aggfunc='mean', fill_value=0)
print(PVC,"\n")

   student_id  subject_id  grade
0           1         101     85
1           2         101     90
2           3         102     78
3           4         102     88
4           1         103     92
5           2         103     95
6           3         101     80
7           4         103     85

   subject_id subject_name
0         101         Math
1         102      Science
2         103      History

subject_name  History  Math  Science
student_id
1                  92    85        0
2                  95    90        0
3                   0    80       78
4                  85     0       88

subject_name  History  Math  Science
student_id
1                  92    85        0
2                  95    90        0
3                   0    80       78
4                  85     0       88

subject_name  History  Math  Science
student_id
1                  92    85        0
2                  95    90        0
3                   0    80       78
4                  85     0       88

In [74]:
# Task3_0530. 고객 데이터프레임에서 age가 30 이상이고 spending이 500 이상인 고객을 찾아 출력하세요.
import pandas as pd

# 예제 데이터프레임 생성
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'age': [25, 35, 30, 40, 28],
    'spending': [300, 600, 500, 700, 400]
})
print(customers,"\n")
C_F=customers[(customers['spending'] >= 500) & (customers['age']>= 30)]
C_F

   customer_id     name  age  spending
0            1    Alice   25       300
1            2      Bob   35       600
2            3  Charlie   30       500
3            4    David   40       700
4            5      Eve   28       400

   customer_id     name  age  spending
1            2      Bob   35       600
2            3  Charlie   30       500
3            4    David   40       700

In [77]:
# Task4_0530. 학생 성적 데이터프레임에서 math_score가 80 이상 90 이하인 학생을 찾아 출력하세요.
import pandas as pd

# 예제 데이터프레임 생성
students = pd.DataFrame({
    'student_id': [101, 102, 103, 104, 105],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'math_score': [75, 85, 88, 92, 78],
    'english_score': [80, 78, 82, 88, 90]
})
print(students,"\n")

S_F=students[(students['math_score'] > 80) & (students['math_score'] <= 90)]
S_F

   student_id     name  math_score  english_score
0         101    Alice          75             80
1         102      Bob          85             78
2         103  Charlie          88             82
3         104    David          92             88
4         105      Eve          78             90

   student_id     name  math_score  english_score
1         102      Bob          85             78
2         103  Charlie          88             82

In [84]:
# Task5_0530. 주어진 titanic3 데이터셋에서 survived 열을 사용하여 생존자와 비생존자의 수를 계산하여 출력하세요.
import pandas as pd

# 데이터프레임 읽기
file_path = '/content/drive/MyDrive/00_KITA_2404/M3_분석라이브러리/pandas/dataset/titanic3.csv'
df = pd.read_csv(file_path)

# 생존자와 비생존자 수 계산
survival_counts = df['survived'].value_counts()
Nom_Null=df.survived.isnull().sum()
# 결과 출력
print(survival_counts)
print(Nom_Null)

survived
0    809
1    500
Name: count, dtype: int64
0

In [93]:
print(df)

      pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton
1          1         1                   Allison, Master. Hudson Trevor
2          1         0                     Allison, Miss. Helen Loraine
3          1         0             Allison, Mr. Hudson Joshua Creighton
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
...      ...       ...                                              ...
1304       3         0                             Zabour, Miss. Hileni
1305       3         0                            Zabour, Miss. Thamine
1306       3         0                        Zakarian, Mr. Mapriededer
1307       3         0                              Zakarian, Mr. Ortin
1308       3         0                               Zimmerman, Mr. Leo

         sex    age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.00      0      0   24160  211.3375       B5        S    2
1       male   0.92      1      2  113781  151.5500  C22 C26        S   11
2     female   2.00      1      2  113781  151.5500  C22 C26        S  NaN
3       male  30.00      1      2  113781  151.5500  C22 C26        S  NaN
4     female  25.00      1      2  113781  151.5500  C22 C26        S  NaN
...      ...    ...    ...    ...     ...       ...      ...      ...  ...
1304  female  14.50      1      0    2665   14.4542      NaN        C  NaN
1305  female    NaN      1      0    2665   14.4542      NaN        C  NaN
1306    male  26.50      0      0    2656    7.2250      NaN        C  NaN
1307    male  27.00      0      0    2670    7.2250      NaN        C  NaN
1308    male  29.00      0      0  315082    7.8750      NaN        S  NaN

       body                        home.dest
0       NaN                     St Louis, MO
1       NaN  Montreal, PQ / Chesterville, ON
2       NaN  Montreal, PQ / Chesterville, ON
3     135.0  Montreal, PQ / Chesterville, ON
4       NaN  Montreal, PQ / Chesterville, ON
...     ...                              ...
1304  328.0                              NaN
1305    NaN                              NaN
1306  304.0                              NaN
1307    NaN                              NaN
1308    NaN                              NaN

[1309 rows x 14 columns]

In [ ]:
df[df['']]

In [92]:
# Task6_0530. 주어진 titanic3 데이터셋에서 pclass 열을 기준으로 각 객실 등급의 평균 운임(fare)을 계산하여 출력하세요.
print(df.columns)
df[['pclass', 'fare']]
PVT=df.pivot_table(index='pclass', values='fare', aggfunc='mean')
PVT

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

             fare
pclass
1       87.508992
2       21.179196
3       13.302889

In [ ]:
# Task7_0530. titanic3 각 변수의 상관계수를 통해 각 변수와 목표 변수(생존 여부) 간의 관계를 파악하세요.
df.corr()

## 하다가 중간에 문자 같은 거는 drop시키고 진행

In [ ]:
# Task8_0530. 승객의 가족 크기(동반한 형제자매/배우자 수와 부모/자녀 수의 합)가 생존에 영향을 미치는지를 탐색하여 결과를 출력하세요.

In [25]:
# Task9_0530. 객실 등급별 평균 요금(mean_fare_by_pclass)이 생존에 미치는 영향을 분석하기 위해 mean_fare_by_pclass라는 파생 변수를 생성하여 출력하세요.
df[['pclass','fare']]

NameError: name 'tdf' is not defined

In [ ]:
#

In [ ]:
#